#!/bin/bash
# genproj

dir=$(dirname $(dirname $(realpath $0)))

project() {
    proj=$1; type=$2; main=$3; targ=$4; name=${proj%%-*}
    sed -e "s:@PROJNAME@:$name:" \
        -e "s:@TARGET@:$targ:" \
        -e "s:@PROJDIR@:$dir/$proj:" \
        -e "s:@MICROBIAN@:$dir/microbian:" \
        -e "s:@MAINFILE@:$dir/$proj/$main:" \
        -e "/^FILE_NAME/s:/:%2F:g" \
        $dir/setup/$type.geany >$dir/$proj/$name.geany
}


project x1000-echo part2 echo.c echo.hex
project x1100-instrs part1 func.s func.hex
project x2100-serial part2 primes.c primes.hex
project x2400-neopixels part2 rainbow.c rainbow.hex
